<?php

namespace JamstackPress\Admin;

class Kernel
{

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

	protected static $jamstackpress_settings_options;



	public static function jamstackpress_settings_add_plugin_page() {
		add_menu_page(
			'JAMStackPress Settings', // page_title
			'JAMStackPress Settings', // menu_title
			'manage_options', // capability
			'jamstackpress', // menu_slug
			[static::class, 'jamstackpress_settings_create_admin_page' ], // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public static function jamstackpress_settings_create_admin_page() {
		static::$jamstackpress_settings_options = get_option( 'jamstackpress_settings_option_name' ); ?>

		<div class="wrap">
			<h2>JAMStackPress Settings</h2>
			<p>JAMStackPress Settings</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'jamstackpress_settings_option_group' );
					do_settings_sections( 'jamstackpress-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public static function jamstackpress_settings_page_init() {
		register_setting(
			'jamstackpress_settings_option_group', // option_group
			'jamstackpress_settings_option_name', // option_name
			[static::class, 'jamstackpress_settings_sanitize' ] // sanitize_callback
		);

		add_settings_section(
			'jamstackpress_setting_section', // id
			'Settings', // title
			[static::class, 'jamstackpress_settings_section_info' ], // callback
			'jamstackpress-admin' // page
		);

		add_settings_field(
			'front_base_url_0', // id
			'Front Base URL', // title
			[static::class, 'front_base_url_0_callback' ], // callback
			'jamstackpress-admin', // page
			'jamstackpress_setting_section' // section
		);

		add_settings_field(
			'legible_human_date_1', // id
			'Legible Human Date', // title
			[static::class, 'legible_human_date_1_callback' ], // callback
			'jamstackpress-admin', // page
			'jamstackpress_setting_section' // section
		);

		add_settings_field(
			'full_slug_field_2', // id
			'Full Slug field', // title
			[static::class, 'full_slug_field_2_callback' ], // callback
			'jamstackpress-admin', // page
			'jamstackpress_setting_section' // section
		);

		add_settings_field(
			'front_url_field_3', // id
			'Front URL Field', // title
			[static::class, 'front_url_field_3_callback' ], // callback
			'jamstackpress-admin', // page
			'jamstackpress_setting_section' // section
		);
	}

	public static function jamstackpress_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['front_base_url_0'] ) ) {
			$sanitary_values['front_base_url_0'] = sanitize_text_field( $input['front_base_url_0'] );
		}

		if ( isset( $input['legible_human_date_1'] ) ) {
			$sanitary_values['legible_human_date_1'] = $input['legible_human_date_1'];
		}

		if ( isset( $input['full_slug_field_2'] ) ) {
			$sanitary_values['full_slug_field_2'] = $input['full_slug_field_2'];
		}

		if ( isset( $input['front_url_field_3'] ) ) {
			$sanitary_values['front_url_field_3'] = $input['front_url_field_3'];
		}

		return $sanitary_values;
	}

	public static function jamstackpress_settings_section_info() {
		
	}

	public static function front_base_url_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="jamstackpress_settings_option_name[front_base_url_0]" id="front_base_url_0" value="%s">',
			isset(static::$jamstackpress_settings_options['front_base_url_0'] ) ? esc_attr(static::$jamstackpress_settings_options['front_base_url_0']) : ''
		);
	}

	public static function legible_human_date_1_callback() {
		printf(
			'<input type="checkbox" name="jamstackpress_settings_option_name[legible_human_date_1]" id="legible_human_date_1" value="legible_human_date_1" %s>',
			( isset(static::$jamstackpress_settings_options['legible_human_date_1'] ) &&static::$jamstackpress_settings_options['legible_human_date_1'] === 'legible_human_date_1' ) ? 'checked' : ''
		);
	}

	public static function full_slug_field_2_callback() {
		printf(
			'<input type="checkbox" name="jamstackpress_settings_option_name[full_slug_field_2]" id="full_slug_field_2" value="full_slug_field_2" %s>',
			( isset(static::$jamstackpress_settings_options['full_slug_field_2'] ) &&static::$jamstackpress_settings_options['full_slug_field_2'] === 'full_slug_field_2' ) ? 'checked' : ''
		);
	}

	public static function front_url_field_3_callback() {
		printf(
			'<input type="checkbox" name="jamstackpress_settings_option_name[front_url_field_3]" id="front_url_field_3" value="front_url_field_3" %s>',
			( isset(static::$jamstackpress_settings_options['front_url_field_3'] ) &&static::$jamstackpress_settings_options['front_url_field_3'] === 'front_url_field_3' ) ? 'checked' : ''
		);
	}




    /**
     * Boot the administration kernel.
     * 
     * @return void
     */
    public static function boot()
    {
        

        add_action( 'admin_menu', [static::class, 'jamstackpress_settings_add_plugin_page' ] );
		add_action( 'admin_init', [static::class, 'jamstackpress_settings_page_init' ] );
    }
}