name: lint
on:
  push:
    branches:
      - 'v1'

  pull_request:
    paths:
      - '**.php'

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: composer install

      - name: PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix src --config=.php-cs-fixer.php

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: code-lint
          skip_fetch: true
