name: lint
on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'PHP-CS-Fixer'
        uses: docker://oskarstartk/php-cs-fixer-ga
        with:
          args: --config=".php-cs-fixer.php"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: code-lint
          skip_fetch: true
